[package]
name = "turbo-spoon"
version = "0.1.0"
authors = ["Heng-Yi Wu <2316687+henry40408@users.noreply.github.com>"]
edition = "2018"
description = "A daemon and CLI to update DNS records on Cloudflare"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloudflare-rs = "0.6.6"
structopt = "0.3.21"
